### ISSUE TITLE
Whether the output results of portcullis can be supported ？

### ISSUE THREAD

**Issue by XXH123a** [yutingsdu/TransMeta#4]
Dear Dr Du Yuting,
It can be said from the original article that the assembly results of Transmeta are far ahead, and the installation instructions are very detailed. I successfully installed and ran the test data, but TM does not support portcullis（ https://github.com/EI-CoreBioinformatics/portcullis , splice junction analysis and filtering from BAM files), psiclass support. Do you think it is necessary to use portcullis or can you support its output?
`TransMeta_outdir exists already. It will be overwritten.
transmeta_graph: assembler.cpp:589: void Assembler::markDuplicates(Assembler::BamYu&, Assembler::FirstReadsYu*, Assembler::ReadPairsYu*): Assertion `current_alignment.start_pos == current_alignment.mate_pos' failed.
transmeta_graph: assembler.cpp:589: void Assembler::markDuplicates(Assembler::BamYu&, Assembler::FirstReadsYu*, Assembler::ReadPairsYu*): Assertion `current_alignment.start_pos == current_alignment.mate_pos' failed.
/home/xxh/all_data/Bio_soft/Big_tools/TransMeta/TransMeta: line 200: 99305 Aborted                 (core dumped) `

**Comment by yutingsdu** [comment]
Hi,
We sorry that the current version of TransMeta doesn't support potcullis, since it depends on the raw information of the BAM files. 
In the TransMeta package, we also have some operations to remove bad splicing junctions, we think maybe portcullis is not necessary for TransMeta.
